### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by yakhinvadim** [repeat-space/anki-apkg-export#33]
Hey, @ewnd9!

How do you feel about updating dependencies for this project? I'd be glad to do it myself and make a PR if you're busy.

**Comment by ewnd9** [comment]
Hey :wave: 

> I'd be glad to do it myself and make a PR if you're busy.

It would be very nice :+1:

**Comment by yakhinvadim** [comment]
Closed by https://github.com/repeat-space/anki-apkg-export/pull/34. Thank you, @jamsinclair!
