### ISSUE TITLE
support for subdecks

### ISSUE THREAD

**Issue by aalemayhu** [repeat-space/anki-apkg-export#42]
I was eyeballing the code and it does not look like subdecks are supported? If that's right is there any plans on adding that? I have two websites\[0]\[1] which uses this cool project and I was hoping to add support for subdecks.

Thanks.

\[0]: http://notion2anki.alemayhu.com/
\[1]: https://workflowy2anki.alemayhu.com/

**Comment by ashlinchak** [comment]
Anki supports the creation of subdecks via naming convention: `Deck::Subdeck`. If you create a title with `::` separator, it'd be treated by Anki as a parent and nested deck.

**Comment by aalemayhu** [comment]
@ashlinchak I did see that in the manual and am using that now but I want to provide one deck file to users to keep things easy.  Currently they need to import multiple decks with the way I am using anki-apkg-export.  It would be simpler with one grouped APKG file that has the tree structure. 

As far as I can see this module does not support it and you have to name your decks correctly and import individually. I would love to use some function call to automate this away so I can group or pick where a card is added before making the save for APKG. It's just for convenience 😄 

Do you know of any other projects which handle subdecks? I looked at the Ruby version but it does not support it either. Would preferably like to keep using this project but also open to switch or add the support myself. 

Thanks.

**Comment by ashlinchak** [comment]
@scanf I don't know about any other projects, that could give you an idea, except Anki itself :smile:  Take a look at how [decks](https://github.com/ankitects/anki/blob/master/pylib/anki/decks.py) are implemented in the desktop version. Also, investigate the importing part if it's possible to do what you need.

**Comment by aalemayhu** [comment]
I experimented with genanki and have removed anki-apkg-export from my project. It's not ideal to shell out to python but it works. I am closing this issue but feel free to re-open 👍🏾 

Thanks 🙏🏾
